### ISSUE TITLE
Do not request resource from classloader using path with leading slash

### ISSUE THREAD

**Issue by DaddyBux43** [mturlo/intellij-spacegray#16] opened 2021-10-16 21:27 UTC
com.intellij.diagnostic.PluginException: /themes/spacegray-mt.xml [Plugin: com.github.mturlo.intellij.theme.spacegray]
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:472)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:439)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
	at com.mallowigi.idea.MTBundledThemesManager.loadBundledTheme(MTBundledThemesManager.java:150)
	at com.mallowigi.idea.MTBundledThemesManager.installBundledTheme(MTBundledThemesManager.java:113)
	at com.mallowigi.idea.MTBundledThemesManager.loadBundledThemes(MTBundledThemesManager.java:108)
	at com.mallowigi.idea.MTLafComponent.initComponent(MTLafComponent.java:115)
	at com.mallowigi.idea.MTLafComponent.appFrameCreated(MTLafComponent.java:74)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:624)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy35.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter.openProjectIfNeeded(IdeStarter.kt:98)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:77)
	at com.intellij.idea.ApplicationLoader$startApp$3.run(ApplicationLoader.kt:185)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by mturlo** [comment] 2021-10-19 11:27
Duplicate of #15

**Closed as completed by mturlo** 2021-10-19 11:27 UTC
