### ISSUE TITLE
PHPStorm exception on start

### ISSUE THREAD

**Issue by m1khal3v** [mturlo/intellij-spacegray#14] opened 2021-08-17 10:37 UTC
Despite the error, the theme works

PHPStorm info:
```
PhpStorm 2021.2
Build #PS-212.4746.100, built on July 28, 2021
Licensed to AO EETP / Anton Mikhalev
You have a perpetual fallback license for this version.
Subscription is active until October 11, 2022.
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.13.11-051311-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1930M
Cores: 12
Registry: run.processes.with.pty=TRUE, ide.experimental.ui.toolwindow.stripes=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X (2021.2), com.andrey4623.rainbowcsv (2.0), com.intellij.ideolog (203.0.27.0), jp.roundrop.sqlformatter (0.1), zielu.gittoolbox (212.7.6), com.jetbrains.upsource (2020.1.1924.11), com.mallowigi (38.0.0), mobi.hsz.idea.gitignore (4.2.0), name.kropp.intellij.makefile (212.4746.52), com.chrisrm.idea.MaterialThemeUI (6.8.0.1), com.github.mturlo.intellij.theme.spacegray (1.4.2), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.4), de.espend.idea.php.annotation (8.0.0), de.espend.idea.php.phpunit (6.0), fr.adrienbrault.idea.symfony2plugin (0.23.211), ru.adelf.idea.dotenv (2021.3.0.212), izhangzhihao.rainbow.brackets (6.19)
Current Desktop: ubuntu:GNOME
```

Stacktrace:
```
Do not request resource from classloader using path with leading slash

com.intellij.diagnostic.PluginException: /themes/spacegray-mt.xml [Plugin: com.github.mturlo.intellij.theme.spacegray]
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:504)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:471)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
	at com.mallowigi.idea.MTBundledThemesManager.loadBundledTheme(MTBundledThemesManager.java:126)
	at com.mallowigi.idea.MTBundledThemesManager.loadBundledThemes(MTBundledThemesManager.java:95)
	at com.mallowigi.idea.MTLafComponent.initComponent(MTLafComponent.java:115)
	at com.mallowigi.idea.MTLafComponent.appFrameCreated(MTLafComponent.java:74)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:624)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy35.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter.openProjectIfNeeded(IdeStarter.kt:98)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:77)
	at com.intellij.idea.ApplicationLoader$startApp$3.run(ApplicationLoader.kt:185)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by mturlo** [comment] 2021-08-19 11:03
Thanks for the detailed report, Anton. Seems like the same thing as in #15. I'm not really experiencing it on MacOS myself - I wonder if it's platform-specific.

**Comment by mturlo** [comment] 2021-10-19 11:27
Duplicate of #15

**Closed as completed by mturlo** 2021-10-19 11:27 UTC
